[package]
name = "requests_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proxyapi = {path = "../proxyapi"}
bytes = "1.4.0"
brotli2 = "0.3.2"
flate2 = "1.0.25"
